USE [master]
BACKUP LOG [ApressFinancial] TO  DISK = N'C:\APRESS_DEV1\MSSQL12.APRESS_DEV1\MSSQL\Backup\ApressFinancial_LogBackup_2014-08-24_15-26-04.bak' WITH NOFORMAT, NOINIT,  NAME = N'ApressFinancial_LogBackup_2014-08-24_15-26-04', NOSKIP, NOREWIND, NOUNLOAD,  NORECOVERY ,  STATS = 5
RESTORE DATABASE [ApressFinancial] FROM  DISK = N'C:\APRESS_DEV1\MSSQL12.APRESS_DEV1\MSSQL\Backup\Test2' WITH  FILE = 1,  NORECOVERY,  NOUNLOAD,  REPLACE,  STATS = 5
RESTORE DATABASE [ApressFinancial] FROM  DISK = N'C:\APRESS_DEV1\MSSQL12.APRESS_DEV1\MSSQL\Backup\Test2' WITH  FILE = 2,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [ApressFinancial] FROM  DISK = N'C:\APRESS_DEV1\MSSQL12.APRESS_DEV1\MSSQL\Backup\Test2' WITH  FILE = 3,  NORECOVERY,  NOUNLOAD,  STATS = 5
RESTORE LOG [ApressFinancial] FROM  DISK = N'C:\APRESS_DEV1\MSSQL12.APRESS_DEV1\MSSQL\Backup\ApressFinancial_LogBackup_2014-08-24_15-26-04.bak' WITH  NOUNLOAD,  STATS = 5,  STOPAT = N'2014-08-24T15:22:33'

GO


