USE ApressFinancial
GO
CREATE UNIQUE CLUSTERED INDEX IX_TransactionTypes 
ON TransactionDetails.TransactionTypes 
(
    TransactionTypeId ASC ) 
WITH (STATISTICS_NORECOMPUTE = ON, SORT_IN_TEMPDB = ON,
 DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = ON,
 ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
ON [PRIMARY] 
GO
CREATE NONCLUSTERED INDEX IX_Transactions_TType 
ON TransactionDetails.Transactions 
(
    TransactionType ASC) 
WITH (STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = ON,
DROP_EXISTING = OFF, IGNORE_DUP_KEY = OFF, ONLINE = ON,
ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) 
ON [PRIMARY]
GO
ALTER TABLE TransactionDetails.TransactionTypes 
ADD CONSTRAINT
    PK_TransactionTypes PRIMARY KEY NONCLUSTERED 
    (
    TransactionTypeId
    ) 
WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF,
ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
ON [PRIMARY]
GO
